name: Sync Commits to Second Repo

on:
  push:
    branches:
      - main # Trigger on push to the main branch (update if your default branch is different)

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the first repository
    - name: Checkout source repository
      uses: actions/checkout@v3

    # Step 2: Configure Git credentials for the second repository
    - name: Configure Git
      run: |
        git config --global user.name "Lithara"
        git config --global user.email "litharaperera2002@gmail.com"
    # Step 3: Add second repository as a remote
    - name: Add second repository as remote
      run: git remote add second-repo https://Lithara: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@github.com/Lithara/plex.lk.git

    # Step 4: Push changes to the second repository
    - name: Push to second repository
      run: |
        git fetch second-repo
        git push second-repo main
